const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arena=$('#arena'),court=$('#court'),game=$('#game'),fx=$('#fx'),cx=court.getContext('2d'),gx=game.getContext('2d'),fxc=fx.getContext('2d');
let W=0,H=0,DPR=Math.min(devicePixelRatio||1,2),raf,last=0,charging=false,charge=0,over=true,started=false,balls=[],parts=[],mode='classic',aiTimer=1,wind=0,hoop={x:.66,y:.36},soundOn=true;
const today=new Date().toISOString().slice(0,10),bots=[['Rookie Bot',.34,1.9],['Normal AI',.46,1.6],['Hard AI',.62,1.28],['Pro AI',.76,1.05]],state=JSON.parse(localStorage.bvaiProFull||'{}');
state.level??=1;state.xp??=0;state.coins??=150;state.wins??=0;state.best??=0;state.perfect??=0;state.ach??={};if(state.day!==today){state.day=today;state.daily={perfect:0,wins:0,hard:0,shots:0,combo:0}}state.daily??={perfect:0,wins:0,hard:0,shots:0,combo:0};
function save(){localStorage.bvaiProFull=JSON.stringify(state)}
function botIndex(){return Math.min(3,Math.floor((state.level-1)/2)+Math.floor(state.wins/4))}
function bot(){return bots[botIndex()]}
function audio(kind){if(!soundOn)return;const AC=window.AudioContext||window.webkitAudioContext;if(!window.ac)window.ac=new AC();const o=ac.createOscillator(),g=ac.createGain();o.type=kind==='miss'?'sawtooth':kind==='win'?'triangle':'sine';o.frequency.value={tap:440,perfect:880,miss:130,win:660,lose:180,level:990,ach:740}[kind]||420;g.gain.value=.055;o.connect(g);g.connect(ac.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.18);o.stop(ac.currentTime+.22)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function resize(){const r=arena.getBoundingClientRect();W=r.width;H=r.height;[court,game,fx].forEach(c=>{c.width=W*DPR;c.height=H*DPR;c.style.width=W+'px';c.style.height=H+'px';c.getContext('2d').setTransform(DPR,0,0,DPR,0,0)});drawCourt();draw()}
addEventListener('resize',resize,{passive:true});
function drawCourt(){cx.clearRect(0,0,W,H);const gr=cx.createLinearGradient(0,0,0,H);gr.addColorStop(0,'#12213a');gr.addColorStop(1,'#07101f');cx.fillStyle=gr;cx.fillRect(0,0,W,H);cx.fillStyle='rgba(255,122,42,.08)';cx.fillRect(0,H*.75,W,H*.25);cx.strokeStyle='rgba(255,255,255,.16)';for(let i=1;i<8;i++){cx.beginPath();cx.moveTo(W*i/8,0);cx.lineTo(W*i/8,H);cx.stroke()}cx.beginPath();cx.arc(W*.5,H*.75,90,0,Math.PI*2);cx.stroke()}
function start(){started=true;over=false;cancelAnimationFrame(raf);mode=$('input[name="mode"]:checked').value;state.p=0;state.a=0;state.left=mode==='blitz'?35:60;state.combo=0;aiTimer=1.35;wind=0;balls=[];parts=[];$('#sp').textContent=0;$('#sa').textContent=0;$('#tm').textContent=Math.ceil(state.left);$('#aiName').textContent=bot()[0];$('#modeTag').textContent=({classic:'Clasic',blitz:'Blitz',moving:'Coș mobil',wind:'Vânt',bank:'Bank lab'}[mode]||mode)+' · '+bot()[0];$('#end').classList.remove('show');$('#tutorial').classList.remove('show');last=performance.now();raf=requestAnimationFrame(loop)}
function loop(t){const dt=Math.min(.033,(t-last)/1000||.016);last=t;if(over)return;state.left-=dt;if(state.left<=0)return finish();$('#tm').textContent=Math.ceil(state.left);if(mode==='moving')hoop.x=.62+Math.sin(t/540)*.14;wind=mode==='wind'?Math.sin(t/500)*.6:0;updateAI(dt);updateBalls();draw();raf=requestAnimationFrame(loop)}
function updateAI(dt){if(!started||over)return;aiTimer-=dt;if(aiTimer>0)return;const b=bot();aiTimer=b[2]+Math.random()*.55;if(Math.random()<b[1]){state.a+=botIndex()>=2?3:2;$('#sa').textContent=state.a;pop(W*.82,H*.34,'+AI','#4ad9ff');audio('tap')}}
function beginCharge(e){if(over||charging)return;charging=true;charge=0;$('#shoot').classList.add('down');try{e.currentTarget.setPointerCapture(e.pointerId)}catch{}}
function endCharge(){if(!charging||over)return;charging=false;$('#shoot').classList.remove('down');shootBall()}
function shootBall(){state.daily.shots++;const aim=+$('#aim').value/45,sweet=charge>.58&&charge<.8,tx=W*hoop.x+aim*38+(sweet?0:(Math.random()-.5)*78),ty=H*hoop.y;balls.push({x:W*.2,y:H*.8-56,vx:(tx-W*.2)/52,vy:(ty-(H*.8-56))/52-5,good:sweet});audio('tap');save();renderHub()}
function updateBalls(){for(let i=balls.length-1;i>=0;i--){const b=balls[i];b.vx+=wind;b.x+=b.vx;b.y+=b.vy;b.vy+=.18;const hx=W*hoop.x,hy=H*hoop.y;if(Math.abs(b.x-hx)<30&&b.y>hy-12&&b.y<hy+12&&b.vy>0){if(b.good&&Math.abs(b.x-hx)<18){const pts=mode==='bank'?3:2;state.p+=pts;state.perfect++;state.daily.perfect++;state.combo++;state.daily.combo=Math.max(state.daily.combo,state.combo);state.best=Math.max(state.best,state.p);$('#sp').textContent=state.p;pop(hx,hy,'PERFECT +'+pts,'#ffd23b');unlock('first','🏀 First Bucket');if(state.combo>=5)unlock('fire','🔥 On Fire');if(mode==='bank')unlock('bank','🏦 Bank Artist');audio('perfect')}else{state.combo=0;pop(hx,hy,'RATARE','#ff5d8f');audio('miss')}balls.splice(i,1);save();renderHub()}else if(b.y>H+50||b.x<-50||b.x>W+50){state.combo=0;balls.splice(i,1)}}}
function pop(x,y,text,color){parts.push({x,y,text,color,life:64})}
function draw(){gx.clearRect(0,0,W,H);fxc.clearRect(0,0,W,H);drawHoop();drawPlayer(.2,.8,'#ff7a2a','TU');drawPlayer(.82,.8,'#4ad9ff','AI');for(const b of balls){gx.fillStyle='#ff8a2a';gx.beginPath();gx.arc(b.x,b.y,13,0,7);gx.fill();gx.strokeStyle='rgba(40,18,5,.75)';gx.lineWidth=3;gx.beginPath();gx.moveTo(b.x-11,b.y);gx.lineTo(b.x+11,b.y);gx.moveTo(b.x,b.y-11);gx.lineTo(b.x,b.y+11);gx.stroke()}for(let i=parts.length-1;i>=0;i--){const p=parts[i];p.life--;fxc.globalAlpha=Math.max(0,p.life/64);fxc.fillStyle=p.color;fxc.font='900 18px system-ui';fxc.fillText(p.text,p.x-42,p.y-p.life*.45);fxc.globalAlpha=1;if(p.life<=0)parts.splice(i,1)}if(charging){charge=Math.min(1,charge+.018);$('#fill').style.width=charge*100+'%'}else $('#fill').style.width='0%'}
function drawHoop(){const x=W*hoop.x,y=H*hoop.y;gx.strokeStyle='#fff';gx.lineWidth=7;gx.beginPath();gx.moveTo(x+42,y-55);gx.lineTo(x+42,y+42);gx.stroke();gx.fillStyle='#fff';gx.fillRect(x+18,y-58,52,38);gx.strokeStyle='#ff7a2a';gx.lineWidth=6;gx.beginPath();gx.ellipse(x,y,34,10,0,0,7);gx.stroke()}
function drawPlayer(px,py,color,label){const x=W*px,y=H*py;gx.fillStyle=color;gx.beginPath();gx.arc(x,y-70,18,0,7);gx.fill();gx.strokeStyle=color;gx.lineWidth=10;gx.lineCap='round';gx.beginPath();gx.moveTo(x,y-52);gx.lineTo(x,y-12);gx.moveTo(x,y-32);gx.lineTo(x+34*(px<.5?1:-1),y-48);gx.moveTo(x,y-12);gx.lineTo(x-20,y+24);gx.moveTo(x,y-12);gx.lineTo(x+22,y+24);gx.stroke();gx.fillStyle='#fff';gx.font='900 12px system-ui';gx.fillText(label,x-12,y-82)}
function finish(){over=true;started=false;cancelAnimationFrame(raf);const win=state.p>=state.a;state.xp+=win?55:20;state.coins+=win?95:25;if(win){state.wins++;state.daily.wins++;if(botIndex()>=2)state.daily.hard++;unlock('win','👑 AI Crusher');audio('win')}else audio('lose');while(state.xp>=state.level*120){state.xp-=state.level*120;state.level++;toast('⬆️ Level '+state.level+'! AI mai puternic');audio('level');unlock('level','🌟 Rising Star')}$('#endTitle').textContent=win?'VICTORIE!':'ÎNFRÂNGERE';$('#endText').textContent=`Scor ${state.p}-${state.a}. Nivel ${state.level}, monede ${state.coins}, best ${state.best}.`;$('#end').classList.add('show');save();renderHub()}
function unlock(k,msg){if(state.ach[k])return;state.ach[k]=true;toast(msg+' deblocat');audio('ach');save()}
function renderHub(){const d=state.daily;$('#dailyTag').textContent=`Daily: ${Math.min(10,d.perfect)}/10`;const daily=[['🎯 10 perfect shots',d.perfect,10,'+120 coins'],['🏆 Win 3 matches',d.wins,3,'+180 coins'],['👑 Beat Hard AI',d.hard,1,'+220 coins'],['🔥 Combo x5',d.combo,5,'+100 coins']];$('#dailyGrid').innerHTML=daily.map(x=>`<div class="card"><strong>${x[0]}</strong><p>${Math.min(x[1],x[2])} / ${x[2]} · ${x[3]}</p><div class="prog"><i style="width:${Math.min(100,x[1]/x[2]*100)}%"></i></div></div>`).join('');const ach=[['first','🏀 First Bucket','Marchează primul coș perfect.'],['fire','🔥 On Fire','Fă combo x5.'],['bank','🏦 Bank Artist','Marchează în Bank lab.'],['win','👑 AI Crusher','Câștigă un meci.'],['level','🌟 Rising Star','Crește în nivel.']];$('#achGrid').innerHTML=ach.map(a=>`<div class="card"><strong>${a[1]}</strong><p>${a[2]}</p><span class="tag ${state.ach[a[0]]?'gold':''}">${state.ach[a[0]]?'Unlocked':'Locked'}</span></div>`).join('');$('#statsGrid').innerHTML=[['Nivel',state.level],['XP',state.xp],['Monede',state.coins],['Best',state.best],['Perfecte',state.perfect],['Victorii',state.wins],['AI curent',bot()[0]],['Dificultate',botIndex()+1+'/4']].map(s=>`<div class="card"><strong>${s[1]}</strong><p>${s[0]}</p></div>`).join('');save()}
$('#shoot').addEventListener('pointerdown',beginCharge,{passive:false});$('#shoot').addEventListener('pointerup',endCharge,{passive:false});$('#shoot').addEventListener('pointercancel',endCharge,{passive:false});addEventListener('pointerup',endCharge,{passive:true});$('#start').onclick=start;$('#again').onclick=start;$('#sound').onclick=()=>{soundOn=!soundOn;$('#sound').textContent=soundOn?'🔊 Sound ON':'🔇 Sound OFF';audio('tap')};$('#tutorialBtn').onclick=()=>$('#tutorial').classList.add('show');$('#ok').onclick=()=>{localStorage.bvaiProTutorial='1';$('#tutorial').classList.remove('show')};$('#reset').onclick=()=>{localStorage.removeItem('bvaiProFull');location.reload()};$$('input[name="mode"]').forEach(i=>i.onchange=()=>{if(!over)start()});resize();renderHub();draw();if(!localStorage.bvaiProTutorial)$('#tutorial').classList.add('show');